settings:
  reverting_tx_gas_limit: true
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
etherscan:
  apiKey: ${ETHERSCAN_TOKEN}
networks:
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    reverting_tx_gas_limit: true
    gas_price: 35
    max_fee: 1.5
    priority_fee: 1.5
  rinkeby:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
  arbtest:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    reverting_tx_gas_limit: true
    gas_limit: 100000000
